# Generated by Django 5.0.8 on 2024-08-30 11:08

import apps.users.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.managers.CustomUserManager()),
            ],
        ),
    ]
