# Generated by Django 5.0.8 on 2024-08-30 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_alter_surveyresponse_unique_together_questionanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswerQuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('question_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='surveys.questionanswer')),
                ('question_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.questionchoice')),
            ],
            options={
                'unique_together': {('question_answer', 'question_choice')},
            },
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='question_choices',
            field=models.ManyToManyField(through='surveys.QuestionAnswerQuestionChoice', to='surveys.questionchoice'),
        ),
    ]
