# Generated by Django 5.0.8 on 2024-08-31 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_questionanswerquestionchoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionalBlocking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking_choices', to='surveys.questionchoice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_questions', to='surveys.question')),
            ],
            options={
                'unique_together': {('choice', 'question')},
            },
        ),
    ]
